import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Plus, Syringe, Calendar, Download, Bell, QrCode, ArrowLeft, Bug } from 'lucide-react';
import { VaccinationCard } from '@/components/vaccinations/VaccinationCard';
import { VaccinationTimeline } from '@/components/vaccinations/VaccinationTimeline';
import { AddVaccineDialog } from '@/components/vaccinations/AddVaccineDialog';
import { VaccinationCalendar } from '@/components/vaccinations/VaccinationCalendar';
import { useNavigate } from 'react-router-dom';

const Vaccinations = () => {
  const navigate = useNavigate();
  const [selectedPet, setSelectedPet] = useState<any>(null);
  const [isAddVaccineOpen, setIsAddVaccineOpen] = useState(false);

  // Mock pets data
  const pets = [
    {
      id: 1,
      name: 'Lucos',
      type: 'Perro',
      breed: 'Cocker Spaniel',
      age: 25,
      birthDate: '2022-09-15',
      avatar: '/placeholder.svg',
    },
    {
      id: 2,
      name: 'Asdads',
      type: 'Perro',
      breed: 'Golden Retriever',
      age: 3,
      birthDate: '2021-06-20',
      avatar: '/placeholder.svg',
    },
    {
      id: 3,
      name: 'Pepe',
      type: 'Gato',
      breed: 'Persa',
      age: 5,
      birthDate: '2019-03-10',
      avatar: '/placeholder.svg',
    }
  ];

  // Mock vaccination and deworming data generated by "AI"
  const vaccinationPlans = {
    1: {
      applied: [
        {
          id: 1,
          name: 'Parvovirus',
          type: 'vaccine' as const,
          date: '2023-10-15',
          nextDose: null,
          veterinarian: 'Dr. García',
          clinic: 'Veterinaria Central',
          lot: 'PV2023-445',
          status: 'completed'
        },
        {
          id: 2,
          name: 'Moquillo',
          type: 'vaccine' as const,
          date: '2023-10-15',
          nextDose: null,
          veterinarian: 'Dr. García',
          clinic: 'Veterinaria Central',
          lot: 'MQ2023-112',
          status: 'completed'
        },
        {
          id: 11,
          name: 'Desparasitación Interna',
          type: 'deworming' as const,
          date: '2024-09-10',
          nextDose: '2024-12-10',
          veterinarian: 'Dr. García',
          clinic: 'Veterinaria Central',
          product: 'Drontal Plus',
          status: 'completed'
        }
      ],
      upcoming: [
        {
          id: 3,
          name: 'Rabia',
          type: 'vaccine' as const,
          dueDate: '2024-12-01',
          recommendedAge: '12 meses',
          importance: 'high',
          description: 'Vacuna obligatoria contra la rabia',
          daysUntil: 45
        },
        {
          id: 4,
          name: 'Refuerzo Parvovirus',
          type: 'vaccine' as const,
          dueDate: '2025-10-15',
          recommendedAge: 'Anual',
          importance: 'medium',
          description: 'Refuerzo anual recomendado',
          daysUntil: 350
        },
        {
          id: 12,
          name: 'Desparasitación Trimestral',
          type: 'deworming' as const,
          dueDate: '2024-12-10',
          recommendedAge: 'Cada 3 meses',
          importance: 'high',
          description: 'Desparasitación interna preventiva',
          daysUntil: 55
        }
      ]
    },
    2: {
      applied: [
        {
          id: 5,
          name: 'Parvovirus',
          type: 'vaccine' as const,
          date: '2024-08-10',
          nextDose: '2025-08-10',
          veterinarian: 'Dr. Martínez',
          clinic: 'Clínica Mascota Feliz',
          lot: 'PV2024-889',
          status: 'completed'
        },
        {
          id: 13,
          name: 'Pipeta Antiparasitaria',
          type: 'deworming' as const,
          date: '2024-10-01',
          nextDose: '2024-11-01',
          veterinarian: 'Dr. Martínez',
          clinic: 'Clínica Mascota Feliz',
          product: 'Frontline Combo',
          status: 'completed'
        }
      ],
      upcoming: [
        {
          id: 6,
          name: 'Rabia',
          type: 'vaccine' as const,
          dueDate: '2024-11-20',
          recommendedAge: '3 meses',
          importance: 'high',
          description: 'Vacuna obligatoria contra la rabia',
          daysUntil: 15
        },
        {
          id: 7,
          name: 'Moquillo',
          type: 'vaccine' as const,
          dueDate: '2024-11-25',
          recommendedAge: '3-4 meses',
          importance: 'high',
          description: 'Protección contra moquillo canino',
          daysUntil: 20
        },
        {
          id: 14,
          name: 'Pipeta Externa',
          type: 'deworming' as const,
          dueDate: '2024-11-01',
          recommendedAge: 'Mensual',
          importance: 'high',
          description: 'Protección contra pulgas y garrapatas',
          daysUntil: 5
        }
      ]
    },
    3: {
      applied: [
        {
          id: 8,
          name: 'Triple Felina',
          type: 'vaccine' as const,
          date: '2024-01-15',
          nextDose: '2025-01-15',
          veterinarian: 'Dra. López',
          clinic: 'Centro Veterinario Gatos',
          lot: 'TF2024-334',
          status: 'completed'
        },
        {
          id: 9,
          name: 'Rabia Felina',
          type: 'vaccine' as const,
          date: '2024-01-15',
          nextDose: '2025-01-15',
          veterinarian: 'Dra. López',
          clinic: 'Centro Veterinario Gatos',
          lot: 'RF2024-221',
          status: 'completed'
        },
        {
          id: 15,
          name: 'Desparasitación Interna',
          type: 'deworming' as const,
          date: '2024-08-15',
          nextDose: '2024-11-15',
          veterinarian: 'Dra. López',
          clinic: 'Centro Veterinario Gatos',
          product: 'Milbemax Gatos',
          status: 'completed'
        }
      ],
      upcoming: [
        {
          id: 10,
          name: 'Leucemia Felina',
          type: 'vaccine' as const,
          dueDate: '2024-12-10',
          recommendedAge: 'Anual',
          importance: 'medium',
          description: 'Recomendada para gatos con acceso al exterior',
          daysUntil: 35
        },
        {
          id: 16,
          name: 'Desparasitación Trimestral',
          type: 'deworming' as const,
          dueDate: '2024-11-15',
          recommendedAge: 'Cada 3 meses',
          importance: 'high',
          description: 'Desparasitación interna preventiva',
          daysUntil: 10
        }
      ]
    }
  };

  const selectedPetPlan = selectedPet ? vaccinationPlans[selectedPet.id as keyof typeof vaccinationPlans] : null;

  return (
    <div className="min-h-screen bg-gradient-to-br from-vaccination-accent to-background">
      {/* Header */}
      <header className="bg-card border-b border-border sticky top-0 z-10">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Button
                variant="ghost"
                size="icon"
                onClick={() => navigate('/pets')}
                className="mr-2"
              >
                <ArrowLeft className="w-5 h-5" />
              </Button>
              <div className="w-10 h-10 bg-vaccination-primary rounded-full flex items-center justify-center">
                <Syringe className="w-5 h-5 text-vaccination-primary-foreground" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-foreground">Salud Preventiva</h1>
                <p className="text-muted-foreground text-sm">Vacunas y desparasitación con IA</p>
              </div>
            </div>
            
            <div className="flex gap-2">
              <Button 
                variant="outline"
                size="sm"
                className="hidden sm:flex"
              >
                <Bell className="w-4 h-4 mr-2" />
                Recordatorios
              </Button>
              <Button 
                onClick={() => selectedPet && setIsAddVaccineOpen(true)}
                disabled={!selectedPet}
                className="bg-vaccination-primary hover:bg-vaccination-primary/90 text-vaccination-primary-foreground"
              >
                <Plus className="w-4 h-4 mr-2" />
                <span className="hidden sm:inline">Registrar Tratamiento</span>
                <span className="sm:hidden">Agregar</span>
              </Button>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-6 md:py-8">
        {/* Pet Selection */}
        <div className="mb-6">
          <h2 className="text-sm font-semibold text-muted-foreground mb-3">Selecciona una mascota</h2>
          <div className="flex flex-wrap gap-3">
            {pets.map((pet) => (
              <button
                key={pet.id}
                onClick={() => setSelectedPet(pet)}
                className={`flex items-center gap-3 p-3 rounded-lg border-2 transition-all ${
                  selectedPet?.id === pet.id
                    ? 'border-vaccination-primary bg-vaccination-primary/5'
                    : 'border-border bg-card hover:border-vaccination-primary/50'
                }`}
              >
                <div className="w-12 h-12 rounded-full bg-muted flex items-center justify-center overflow-hidden">
                  <img src={pet.avatar} alt={pet.name} className="w-full h-full object-cover" />
                </div>
                <div className="text-left">
                  <p className="font-semibold text-foreground">{pet.name}</p>
                  <p className="text-xs text-muted-foreground">{pet.breed}</p>
                </div>
              </button>
            ))}
          </div>
        </div>

        {selectedPet && selectedPetPlan ? (
          <div className="grid lg:grid-cols-3 gap-6">
            {/* Main Content */}
            <div className="lg:col-span-2 space-y-6">
              {/* AI-Generated Alert */}
              <Card className="border-vaccination-primary/30 bg-vaccination-primary/5">
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 rounded-full bg-vaccination-primary/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                      <Syringe className="w-4 h-4 text-vaccination-primary" />
                    </div>
                    <div className="flex-1">
                      <p className="font-semibold text-sm mb-1">Plan generado con IA</p>
                      <p className="text-xs text-muted-foreground">
                        Este plan de salud preventiva fue personalizado para <strong>{selectedPet.name}</strong> ({selectedPet.breed}, {selectedPet.age} meses) 
                        e incluye vacunas y desparasitación según las recomendaciones veterinarias.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Stats Cards */}
              <div className="grid sm:grid-cols-4 gap-4">
                <Card>
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-2xl font-bold text-foreground">
                          {selectedPetPlan.applied.filter(v => v.type === 'vaccine').length}
                        </p>
                        <p className="text-xs text-muted-foreground">Vacunas</p>
                      </div>
                      <div className="w-10 h-10 rounded-full bg-green-500/10 flex items-center justify-center">
                        <Syringe className="w-5 h-5 text-green-600" />
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-2xl font-bold text-foreground">
                          {selectedPetPlan.applied.filter(v => v.type === 'deworming').length}
                        </p>
                        <p className="text-xs text-muted-foreground">Desparasitaciones</p>
                      </div>
                      <div className="w-10 h-10 rounded-full bg-blue-500/10 flex items-center justify-center">
                        <Bug className="w-5 h-5 text-blue-600" />
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-2xl font-bold text-foreground">{selectedPetPlan.upcoming.length}</p>
                        <p className="text-xs text-muted-foreground">Próximas</p>
                      </div>
                      <div className="w-10 h-10 rounded-full bg-amber-500/10 flex items-center justify-center">
                        <Calendar className="w-5 h-5 text-amber-600" />
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-2xl font-bold text-foreground">
                          {selectedPetPlan.upcoming.filter(v => v.daysUntil <= 30).length}
                        </p>
                        <p className="text-xs text-muted-foreground">Urgentes</p>
                      </div>
                      <div className="w-10 h-10 rounded-full bg-red-500/10 flex items-center justify-center">
                        <Bell className="w-5 h-5 text-red-600" />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* Tabs Content */}
              <Tabs defaultValue="carnet" className="w-full">
                <TabsList className="grid w-full grid-cols-3">
                  <TabsTrigger value="carnet">Carnet</TabsTrigger>
                  <TabsTrigger value="timeline">Historial</TabsTrigger>
                  <TabsTrigger value="calendar">Calendario</TabsTrigger>
                </TabsList>

                <TabsContent value="carnet" className="mt-6">
                  <VaccinationCard 
                    pet={selectedPet} 
                    appliedVaccines={selectedPetPlan.applied}
                  />
                </TabsContent>

                <TabsContent value="timeline" className="mt-6">
                  <VaccinationTimeline 
                    appliedVaccines={selectedPetPlan.applied}
                    upcomingVaccines={selectedPetPlan.upcoming}
                  />
                </TabsContent>

                <TabsContent value="calendar" className="mt-6">
                  <VaccinationCalendar 
                    upcomingVaccines={selectedPetPlan.upcoming}
                  />
                </TabsContent>
              </Tabs>
            </div>

            {/* Sidebar */}
            <div className="lg:col-span-1 space-y-6">
              {/* Quick Actions */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Acciones Rápidas</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <Button variant="outline" className="w-full justify-start" size="sm">
                    <Download className="w-4 h-4 mr-2" />
                    Descargar Carnet PDF
                  </Button>
                  <Button variant="outline" className="w-full justify-start" size="sm">
                    <QrCode className="w-4 h-4 mr-2" />
                    Ver Código QR
                  </Button>
                  <Button variant="outline" className="w-full justify-start" size="sm">
                    <Bell className="w-4 h-4 mr-2" />
                    Configurar Alertas
                  </Button>
                </CardContent>
              </Card>

              {/* Upcoming Vaccines */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Próximas Vacunas</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {selectedPetPlan.upcoming.map((vaccine) => (
                    <div key={vaccine.id} className="p-3 rounded-lg bg-muted/50 space-y-1">
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex items-center gap-2 flex-1">
                          {vaccine.type === 'vaccine' ? (
                            <Syringe className="w-3.5 h-3.5 text-green-600 flex-shrink-0" />
                          ) : (
                            <Bug className="w-3.5 h-3.5 text-blue-600 flex-shrink-0" />
                          )}
                          <p className="font-semibold text-sm">{vaccine.name}</p>
                        </div>
                        <Badge 
                          variant={vaccine.importance === 'high' ? 'destructive' : 'secondary'}
                          className="text-xs flex-shrink-0"
                        >
                          {vaccine.daysUntil}d
                        </Badge>
                      </div>
                      <p className="text-xs text-muted-foreground">{vaccine.description}</p>
                      <p className="text-xs font-medium text-vaccination-primary">{vaccine.dueDate}</p>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>
          </div>
        ) : (
          <Card className="mt-8">
            <CardContent className="p-12 text-center">
              <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mx-auto mb-4">
                <Syringe className="w-8 h-8 text-muted-foreground" />
              </div>
              <h3 className="text-lg font-semibold mb-2">Selecciona una mascota</h3>
              <p className="text-muted-foreground text-sm max-w-md mx-auto">
                Elige una mascota arriba para ver su plan de salud preventiva personalizado (vacunas y desparasitación)
              </p>
            </CardContent>
          </Card>
        )}
      </div>

      {/* Add Vaccine Dialog */}
      <AddVaccineDialog 
        open={isAddVaccineOpen} 
        onOpenChange={setIsAddVaccineOpen}
        pet={selectedPet}
      />
    </div>
  );
};

export default Vaccinations;
